spring:
  application:
    name: spring-cloud-eureka
  profiles: dev
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/